### ISSUE TITLE
pkgdown::deploy_site_github() fails at git push, does not seem to use SSH

### ISSUE THREAD

**Issue by petrbouchal** [r-lib/pkgdown#1275]
This appeared with pkgdown v1.5, both CRAN and dev.

Log - relevant part:
 
```
── Extra files for GitHub pages ────────────────────────────────────────────────

── Commiting updated site ──────────────────────────────────────────────────────

Running git add -A .

Running git commit --allow-empty -m \

  'Built site for reschola: 0.2.7.9000@e5fbe49'

[gh-pages 738c770] Built site for reschola: 0.2.7.9000@e5fbe49

 43 files changed, 824 insertions(+), 727 deletions(-)

── Deploying to GitHub Pages ───────────────────────────────────────────────────

Running git remote -v

origin	https://github.com/scholaempirica/reschola.git (fetch)

origin	https://github.com/scholaempirica/reschola.git (push)

Running git push --force origin 'HEAD:gh-pages'

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/scholaempirica/reschola.git/'

Error: System command 'git' failed, exit status: 128, stdout & stderr were printed

 Stack trace:

 1. pkgdown::deploy_site_github()

 2. pkgdown:::deploy_to_branch(pkg, commit_message = commit_message,  ...

 3. pkgdown:::github_push(dest_dir, commit_message, remote, branch)

 4. pkgdown:::with_dir(dir, { ...

 5. base:::force(code)

 6. pkgdown:::git("push", "--force", remote, paste0("HEAD:", branch))

 7. processx::run("git", c(...), echo_cmd = echo_cmd, echo = echo,  ...

 8. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'git' failed, exit status: 128, stdout & stderr were printed 

── Removing worktree ───────────────────────────────────────────────────────────

Running git worktree remove /tmp/RtmpC2bjSY/file3a426e51abcd

Execution halted

Script failed with status 1

failed to deploy
```
Travis config:

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

```

Deploying the same code works with pkgdown v1.4.1, i.e. when `before_cache: Rscript -e 'remotes::install_cran("pkgdown")'` is replaced with `before_cache: Rscript -e 'remotes::install_version("pkgdown", version = "1.4.1")'`.

From the log it seems that pkgdown is using HTTPS for pushing to github, which does not seem right given that it should rely on the RSA deploy key.

All builds and logs: https://travis-ci.org/github/scholaempirica/reschola

**Comment by petrbouchal** [comment]
It seems I reported this simultaneously with #1274 - leaving this here in case the extra information here is useful.

**Comment by jimhester** [comment]
I think https://github.com/r-lib/pkgdown/pull/1276 should fix this, but @petrbouchal it would be great for you to test this, e.g. put `remotes::install_github("r-lib/pkgdown#1276")` in your config and see if it works.

**Comment by FelixErnst** [comment]
@jimhester 

Doesn't seem to solve the issue. Know the checkout of the gh-pages branch breaks
https://travis-ci.com/github/FelixErnst/Structstrings/builds/155654019

**Comment by jimhester** [comment]
Thank you for trying it! yes you are right, I saw the failed build, just pushed a new commit that I think should really fix it. 🤞

**Comment by FelixErnst** [comment]
Its already fixed

https://travis-ci.com/github/FelixErnst/Structstrings/builds/155654019

The cache was keeping something to be updated correctly

**Comment by jayhesselberth** [comment]
I can confirm this fixes one of my builds, too.

https://travis-ci.org/github/rnabioco/clustifyr/builds/667426616

**Comment by petrbouchal** [comment]
Yes, can confirm as well that this fixes the problem; the build finishes without errors: https://travis-ci.org/github/scholaempirica/reschola/builds/667455554

Many thanks for the quick fix.
