### ISSUE TITLE
Too narrow paragraphs in Arguments' section

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#1317]
## Last minute edit

I was writing this issue when I realised that the problem here reported seems to be web browser dependent. I only see the issue here reported with chromium and brave, but not with firefox. Because the issue is browser dependent I hesitated whether I should keep it or not. I decided to keep it because the problem seems to be specific to the Arguments section and also because it might be impacting how users see the package online documentation. Not sure if any action is warranted though on pkgdown's side. You guys let me know.

## Issue

The html paragraph width of each argument in the Arguments section is at times too narrow creating a soft wrap of the paragraph.

## Using Chromium or Brave browsers
Here is an example from a package of mine where the paragraph is soft wrapped because of the 70 pixel limit.

![Rf_ScalarLogical](https://user-images.githubusercontent.com/19862384/80687002-87ce8000-8ac1-11ea-9937-3a2beedb0aef.png)

## Using Firefox
![firefox](https://user-images.githubusercontent.com/19862384/80688376-961d9b80-8ac3-11ea-89ac-6b9b1411be48.png)

## rlang, Firefox (left) vs Chromium (right)

This is not something particular to my website generation, I see this happening also with tidyverse packages, e.g., rlang:

- `nlines` argument description is soft wrapped too early: https://rlang.r-lib.org/reference/expr_label.html
- here however the argument description texts seem to take all the space available as I would generally expect: https://rlang.r-lib.org/reference/call_fn.html

![Screenshot from 2020-04-30 09-23-56](https://user-images.githubusercontent.com/19862384/80688721-2825a400-8ac4-11ea-9a33-7c11b8f0a4cc.png)

**Comment by jayhesselberth** [comment]
Related to #1312.

**Comment by jayhesselberth** [comment]
I think this was fixed after merging #1312.

Can you please install the dev version of pkgdown and re-build your site to confirm?

**Comment by ramiromagno** [comment]
Hi,

I installed the dev version, i.e., version `1.5.1.9000`. Start a new R session. Then I deleted all files in `docs/`, and regenerated the whole website again. But the problem persists though.

**Comment by jayhesselberth** [comment]
Can you send a link to a live site illustrating the issue?

**Comment by ramiromagno** [comment]
https://rmagno.eu/c3po/reference/Rf_ScalarLogical.html

**Comment by randy3k** [comment]
@jayhesselberth 
As far as I could tell, it is a different table class `.ref-arguments`. My fix in #1312 was meant to fix the width of the reference table class `.ref-index`.

**Comment by randy3k** [comment]
@ramiromagno 
With that said, I don't think I could reproduce your issue on my chrome:

<img width="518" alt="Screen Shot 2020-05-17 at 12 58 48 PM" src="https://user-images.githubusercontent.com/1690993/82158680-2be45500-983e-11ea-9a5b-f66e9632a958.png">

**Comment by ramiromagno** [comment]
@randy3k: try 80% .

**Comment by randy3k** [comment]
Yap, 80% has the same issue.

**Comment by randy3k** [comment]
I guess the same fix could be applied.

```
.ref-arguments th, .ref-arguments td {vertical-align: top; min-width: 100px}
```
