### ISSUE TITLE
Snapshot errors after new knitr

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2875]
knitr 1.50 was just released, which caused a change in one of the snapshot tests, merged in https://github.com/r-lib/pkgdown/commit/66477c0dbb4f4925ec872cf64d5eaa316cc70bac.

<img width="1448" alt="Image" src="https://github.com/user-attachments/assets/ced04b90-a59b-48b4-aeb0-b68bfaf7295d" />

But now the snapshot errors have a new error on GHA, which I can't trigger locally:

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-build-article.R:256:3'): build_article yields useful error if R fails ──
Snapshot of code has changed:
old[6:10] vs new[6:13]
    Error in `build_article()`:
    ! Failed to render 'vignettes/test.Rmd'.
    x Quitting from test.Rmd:4-9 [unnamed-chunk-1]
-   Caused by error:
-   ! Error!
+   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   x NULL
+   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   Caused by error:
+   ! Error!

* Run `testthat::snapshot_accept('build-article')` to accept the change.
* Run `testthat::snapshot_review('build-article')` to interactively review the change.
── Failure ('test-build-article.R:259:3'): build_article yields useful error if R fails ──
Snapshot of code has changed:
old[7:12] vs new[7:15]
    <error/rlang_error>
    Error in `build_article()`:
    ! Failed to render 'vignettes/test.Rmd'.
    x Quitting from test.Rmd:4-9 [unnamed-chunk-1]
+   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   x NULL
+   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Caused by error:
    ! Error!
    ---

* Run `testthat::snapshot_accept('build-article')` to accept the change.
* Run `testthat::snapshot_review('build-article')` to interactively review the change.
```

@hadley these changes are from your knitr PR https://github.com/yihui/knitr/pull/2390. Any idea why we would see this new error?

Based on the code, `NULL` shouldn't appear in the output at all:

https://github.com/yihui/knitr/blob/bc6404986e72855c7ce9e9fd779e445f42d30a33/R/output.R#L327-L334

**Comment by hadley** [comment]
FWIW I can replicate the error locally. Are you sure you have all the latest deps?

**Comment by hadley** [comment]
Quick fix from evaluate:

```R
# pretend that we're never running inside of R CMD check
withr::local_envvar(
  `_R_CHECK_PACKAGE_NAME_` = NA,
  `_R_CHECK_LICENSE_` = NA,
)
```

This is possibly technically a bug from https://github.com/r-lib/pkgdown/issues/2875, but it only arises when you're running knitr instead your tests (which is relatively rare)

**Comment by hadley** [comment]
Ok I'm leaning towards it actually being a bug because you also see it if you throw an rlang error in a vignette. Possible fix at https://github.com/yihui/knitr/pull/2396.

**Comment by cderv** [comment]
I have worked on 
- https://github.com/yihui/knitr/pull/2388

and it should fix this problem too.

**Comment by jayhesselberth** [comment]
I reran the tests with github knitr, and this test still fails but with a different error:

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-build-article.R:256:3'): build_article yields useful error if R fails ──
Snapshot of code has changed:
old[6:10] vs new[6:21]
    Error in `build_article()`:
    ! Failed to render 'vignettes/test.Rmd'.
    x Quitting from test.Rmd:4-9 [unnamed-chunk-1]
-   Caused by error:
-   ! Error!
+   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   x <error/rlang_error>
+   x Error in `h()`:
+   x ! Error!
+   x ---
+   x Backtrace:
+   x  ▆
+   x  1. └─global f()
+   x  2.  └─global g()
+   x  3.  └─global h()
+   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+   Caused by error:
+   ! Error!
```

https://github.com/r-lib/pkgdown/actions/runs/14241804042/job/39913211343?pr=2881

**Comment by jayhesselberth** [comment]
Oh but maybe this is the expected error now?

**Comment by cderv** [comment]
yes this is the expected error message for failure when vignette building 

- Before: No useful information
- Now: Traceback for the error happening inside the vignette rendering is shown

So you need to update the snapshot

**Comment by jayhesselberth** [comment]
I have never been able to trigger this error locally and am confused as to why.

If someone else can see the error, could you update the snapshot?
